kind: ConfigMap
apiVersion: v1
metadata:
  name: quarkus-camel-razorpay
  labels:
    app: quarkus-camel-razorpay
    app.kubernetes.io/component: quarkus-camel-razorpay
    app.kubernetes.io/instance: quarkus-camel-razorpay
    app.kubernetes.io/name: quarkus-camel-razorpay
    app.kubernetes.io/part-of: java-apps
    app.openshift.io/runtime: quarkus
data:
  APP_TITLE: welcome to quarkus camel razorpay demo
  KAFKA_BOOTSTRAP: kafka_bootstrap_url
type: Opaque
