kind: Secret
apiVersion: v1
metadata:
  name: quarkus-camel-razorpay
  labels:
    app: quarkus-camel-razorpay
    app.kubernetes.io/component: quarkus-camel-razorpay
    app.kubernetes.io/instance: quarkus-camel-razorpay
    app.kubernetes.io/name: quarkus-camel-razorpay
    app.kubernetes.io/part-of: java-apps
    app.openshift.io/runtime: quarkus
data:
  RAZORPAY_KEY: key_base64
  RAZORPAY_SECRET: secret_base64
type: Opaque
