
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: quarkus-camel-controller
  labels:
    strimzi.io/cluster: quarkus-camel
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: persistent-claim
    size: 5Gi
    kraftMetadata: shared
    deleteClaim: true

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: quarkus-camel-broker
  labels:
    strimzi.io/cluster: quarkus-camel
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 5Gi
    kraftMetadata: shared
    deleteClaim: true

---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: quarkus-camel
  namespace: kafka-demo
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: route